name: test

on:
  push:

jobs:
  CodeQualityClient:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'
      - name: Install project dependencies
        working-directory: client
        run: yarn install -s --no-progress
      - name: Run client linter check
        working-directory: client
        run: yarn run lint

  CodeQualityApi:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
      - name: Install project dependencies
        working-directory: api
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Run larastan
        working-directory: api
        run: ./vendor/bin/phpstan --memory-limit=1G analyse

  Setup:
    needs: [CodeQualityClient, CodeQualityApi]
    runs-on: ubuntu-latest
    steps:
    - name: Init
      run: |
        echo setup completed
